### ISSUE TITLE
Stale auth results in token=None, which means the single-user server executes as the parent user

### ISSUE THREAD

**Issue by ociule** [ni/jupyterhub-winauthenticator#4]
This looks tricky. To trigger, one has to restart jupyterhub. In a browser, any connected user is still connected and can try to launch a server. That works, but the server gets launched as the parent admin user that's running jupyterhub.

The cause is complex, auth_state is None and token is None. This gets passed to WinLocalProcessSpawner which cannot differentiate this from not using tokens and launches a single user server as the parent admin user.

Here's the bad patch I made to WinAuthenticator.pre_spawn_start and currently use to at least stop this and tell the users to logout and login:

```diff
diff --git a/winauthenticator/winauthenticator.py b/winauthenticator/winauthenticator.py
index 676b5cd..ff758b2 100644
--- a/winauthenticator/winauthenticator.py
+++ b/winauthenticator/winauthenticator.py
@@ -139,6 +139,9 @@ class WinAuthenticator(LocalAuthenticator):
         try:
             loop = asyncio.new_event_loop()
             auth_state = loop.run_until_complete(user.get_auth_state())
+
+            if not auth_state:
+                raise Exception('Stale auth_state, please logout and login.')
             token = pywintypes.HANDLE(auth_state['auth_token'])
 
             if '@' not in user.name:
@@ -155,6 +158,7 @@ class WinAuthenticator(LocalAuthenticator):
             )
         except Exception as exc:
             self.log.warning("Failed to load user profile for %s: %s", user.name, exc)
+            raise
         finally:
             if token:
                 # Detach so the underlying winhandle stays alive
```

WinAuthenticator.pre_spawn_start gets called by User.spawn, see https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/user.py#L541

However, auth_state is None, yet the user is connected. Hence my temp patch, where I try to detect this and raise the error.

Hopefully there's a better way to detect this condition and force a logout. I don't see any way to refresh auth_state and the token, as win_authenticator does not keep the user's password.

**Comment by adelcast** [comment]
Have you looked at the refresh_pre_spawn method of the base Authenticator class [1]? I believe the token null check can be implemented on refresh_user (if null, return False). If refresh_user returns False, jupyterhub logs out the user (haven't tried this yet, but this is my understanding).

[1] https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py

**Comment by ociule** [comment]
Thanks for the suggestion, works great, PR submitted.
