### ISSUE TITLE
Is there a way to let a visitor demand an account and wait for activation?

### ISSUE THREAD

**Issue by ghost** [ni/jupyterhub-winauthenticator#7]
Now that I could login with a local account, I would like a remote semi-trusted user to register (ask for an account) that probably spawn (after acceptance of Admin) a new account ?

**Comment by adelcast** [comment]
The winauthenticator is not providing this capability...but there might be a way to do it if you want to give it a shot. If you look at the general Authenticator class [1], you'll see there are entrypoints that you can override. Specifically pre_spawn_start or post_auth_hook might give you a way to execute your own code before the notebook server is spawned.

Hope this helps.

[1] https://jupyterhub.readthedocs.io/en/stable/api/auth.html

**Comment by ghost** [comment]
Very nice, I will check that, many thanks.
